Areas/Admin/Controllers/FacebookShopController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Cors;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Nop.Core;
using Nop.Core.Domain.Catalog;
using Nop.Core.Infrastructure;
using Nop.Plugin.NopStation.Core.Controllers;
using Nop.Plugin.NopStation.Core.Filters;
using Nop.Plugin.NopStation.Core.Helpers;
using Nop.Plugin.NopStation.FacebookShop.Areas.Admin.Factories;
using Nop.Plugin.NopStation.FacebookShop.Areas.Admin.Models;
using Nop.Plugin.NopStation.FacebookShop.Domains;
using Nop.Plugin.NopStation.FacebookShop.Services;
using Nop.Services.Catalog;
using Nop.Services.Configuration;
using Nop.Services.Localization;
using Nop.Services.Logging;
using Nop.Services.Messages;
using Nop.Services.Security;
using Nop.Web.Areas.Admin.Infrastructure.Mapper.Extensions;
using Nop.Web.Areas.Admin.Models.Catalog;

namespace Nop.Plugin.NopStation.FacebookShop.Areas.Admin.Controllers
{
    public class FacebookShopController : NopStationAdminController
    {
        #region Properties
        private readonly IPermissionService _permissionService;
        private readonly ISettingService _settingService;
        private readonly IFacebookShopModelFactory _facebookShopModelFactory;
        private readonly IStoreContext _storeContext;
        private readonly INotificationService _notificationService;
        private readonly ILocalizationService _localizationService;
        private readonly IShopItemModelFactory _shopItemModelFactory;
        private readonly IFacebookShopService _facebookShopService;
        private readonly IWorkContext _workContext;
        private readonly ICategoryService _categoryService;
        private readonly IProductService _productService;

        #endregion

        #region Ctor
        public FacebookShopController(IPermissionService permissionService,
          ISettingService settingService,
          IFacebookShopModelFactory facebookShopModelFactory,
          IStoreContext storeContext,
          INotificationService notificationService,
          ILocalizationService localizationService,
          IShopItemModelFactory shopItemModelFactory, IFacebookShopService facebookShopService, IWorkContext workContext, ICategoryService categoryService, IProductService productService)
        {
            _permissionService = permissionService;
            _settingService = settingService;
            _facebookShopModelFactory = facebookShopModelFactory;
            _storeContext = storeContext;
            _notificationService = notificationService;
            _localizationService = localizationService;
            _shopItemModelFactory = shopItemModelFactory;
            _facebookShopService = facebookShopService;
            _workContext = workContext;
            _categoryService = categoryService;
            _productService = productService;
        }
        #endregion

        #region Action Methods
        public async Task<IActionResult> Configure()
        {
            if (!await _permissionService.AuthorizeAsync(FacebookShopPermissionProvider.ManageFacebookShop))
                return AccessDeniedView();

            var model = await _facebookShopModelFactory.PrepareConfigurationModelAsync();
            return View(model);
        }

        [EditAccess, HttpPost]
        public async Task<IActionResult> Configure(ConfigurationModel model)
        {
            if (!await _permissionService.AuthorizeAsync(FacebookShopPermissionProvider.ManageFacebookShop))
                return AccessDeniedView();

            var storeScope = await _storeContext.GetActiveStoreScopeConfigurationAsync();
            var facebookShopSettings = await _settingService.LoadSettingAsync<FacebookShopSettings>(storeScope);
            facebookShopSettings = model.ToSettings(facebookShopSettings);

            await _settingService.SaveSettingOverridablePerStoreAsync(facebookShopSettings, x => x.PrimaryCurrencyId, model.PrimaryCurrencyId_OverrideForStore, storeScope, false);
            await _settingService.SaveSettingOverridablePerStoreAsync(facebookShopSettings, x => x.PrimaryLanguageId, model.PrimaryLanguageId_OverrideForStore, storeScope, false);

            await _settingService.ClearCacheAsync();
            _notificationService.SuccessNotification(await _localizationService.GetResourceAsync("Admin.Configuration.Updated"));

            return RedirectToAction("Configure");
        }

        public async Task<IActionResult> GetGoogleProductCategoriesList()
        {
            try
            {
                var nopFileProvider = NopInstance.Load<INopFileProvider>();
                var filePath = nopFileProvider.Combine(nopFileProvider.MapPath("~/Plugins/NopStation.FacebookShop/"), "GoogleProductCategories.json");

                if (nopFileProvider.FileExists(filePath))
                {
                    var jsonstr = await nopFileProvider.ReadAllTextAsync(filePath, Encoding.UTF8);
                    var list = JsonConvert.DeserializeObject(jsonstr);
                    return Json(list);
                }
            }
            catch (Exception ex)
            {
                NopInstance.Load<ILogger>().ErrorAsync(ex.Message, ex).Wait();
                return StatusCode(StatusCodes.Status500InternalServerError);
            }
            return Json("");
        }

        [IgnoreAntiforgeryToken]
        public async Task<IActionResult> DeleteSelectedProductShopItems(string selectedIds)
        {
            try
            {
                await _facebookShopService.BulkDeleteShopItemAsync(selectedIds);
            }
            catch (Exception ex)
            {
                NopInstance.Load<ILogger>().ErrorAsync(ex.Message, ex).Wait();
                return StatusCode(StatusCodes.Status500InternalServerError);
            }
            return Json("");
        }

        public virtual async Task<IActionResult> BulkItemsAddPopup()
        {
            ViewBag.RefreshPage = false;
            var model = await _shopItemModelFactory.PrepareShopItemModelAsync(new ShopItemModel(), null, new ProductModel());
            return View("_BulkItemsAddPopup", model);
        }
        [HttpPost]
        public virtual async Task<IActionResult> BulkItemsAddPopup(string productIds, ShopItemModel model)
        {
            try
            {
                ViewBag.RefreshPage = true;
                await _facebookShopService.BulkInsertShopItemAsync(productIds, model.ToEntity<ShopItem>());
                _notificationService.SuccessNotification(await _localizationService.GetResourceAsync("Admin.NopStation.FacebookShop.AddedSuccessfully"));
            }
            catch (Exception ex)
            {
                ViewBag.RefreshPage = false;

                return BadRequest(ex.Message);
            }
            return View("_BulkItemsAddPopup", model);
        }

        [HttpPost]
        public virtual async Task<IActionResult> BulkItemsAddAllView(ProductSearchModel productSearchModel)
        {
            ViewBag.RefreshPage = false;
            var shopItemModel = new ShopItemModel { ProductSearchModel = productSearchModel };

            var model = await _shopItemModelFactory.PrepareShopItemModelAsync(shopItemModel, null, new ProductModel());

            return View("_BulkItemsAddAllView", model);
        }
        [HttpPost]
        public virtual async Task<IActionResult> BulkItemsAddAll(ShopItemModel model)
        {
            try
            {
                if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManageProducts))
                    return AccessDeniedView();

                //a vendor should have access only to his products
                if (await _workContext.GetCurrentVendorAsync() != null)
                {
                    model.ProductSearchModel.SearchVendorId = (await _workContext.GetCurrentVendorAsync()).Id;
                }

                var categoryIds = new List<int> { model.ProductSearchModel.SearchCategoryId };
                //include subcategories
                if (model.ProductSearchModel.SearchIncludeSubCategories && model.ProductSearchModel.SearchCategoryId > 0)
                    categoryIds.AddRange(await _categoryService.GetChildCategoryIdsAsync(parentCategoryId: model.ProductSearchModel.SearchCategoryId, showHidden: true));

                //0 - all (according to "ShowHidden" parameter)
                //1 - published only
                //2 - unpublished only
                bool? overridePublished = null;
                if (model.ProductSearchModel.SearchPublishedId == 1)
                    overridePublished = true;
                else if (model.ProductSearchModel.SearchPublishedId == 2)
                    overridePublished = false;

                var products = await _productService.SearchProductsAsync(0,
                    categoryIds: categoryIds,
                    manufacturerIds: new List<int> { model.ProductSearchModel.SearchManufacturerId },
                    storeId: model.ProductSearchModel.SearchStoreId,
                    vendorId: model.ProductSearchModel.SearchVendorId,
                    warehouseId: model.ProductSearchModel.SearchWarehouseId,
                    productType: model.ProductSearchModel.SearchProductTypeId > 0 ? (ProductType?)model.ProductSearchModel.SearchProductTypeId : null,
                    keywords: model.ProductSearchModel.SearchProductName,
                    showHidden: true,
                    overridePublished: overridePublished);

                var productIds = products.Select(item => item.Id).ToArray();
                await _facebookShopService.BulkInsertAllFoundShopItemsAsync(model.ToEntity<ShopItem>(), productIds);

Controllers/FacebookShopCatalogController.cs
using System;
using System.Collections.Generic;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Nop.Core;
using Nop.Core.Infrastructure;
using Nop.Plugin.NopStation.Core.Controllers;
using Nop.Plugin.NopStation.Core.Helpers;
using Nop.Plugin.NopStation.FacebookShop.Services;
using Nop.Services.Logging;

namespace Nop.Plugin.NopStation.FacebookShop.Controllers
{
    public class FacebookShopCatalogController : NopStationPublicController
    {
        #region Properties
        private readonly INopFileProvider _fileProvider;
        private readonly ILogger _logger; 
        #endregion

        #region Ctor
        public FacebookShopCatalogController(INopFileProvider fileProvider,
            ILogger logger)
        {
            _fileProvider = fileProvider;
            _logger = logger;
        } 
        #endregion

        #region Methods
        public async Task<IActionResult> GetCatalogFeed(string fileName)
        {
            try
            {
                var basePath = _fileProvider.MapPath("~/Plugins/NopStation.FacebookShop/Files/");
                var excelFilePath = _fileProvider.Combine(_fileProvider.MapPath(basePath), FacebookShopDefaults.FileName);
                var bytes = await _fileProvider.ReadAllBytesAsync(excelFilePath);
                return File(bytes, MimeTypes.TextXlsx, FacebookShopDefaults.FileName);
            }
            catch (Exception exc)
            {
                await _logger.ErrorAsync($"Failed to get feed: {exc.Message}", exc);
                return StatusCode(StatusCodes.Status500InternalServerError);
            }
        }
        #endregion
    }
}

Areas/Admin/Views/FacebookShop/BulkItemsAddAllView.cshtml
@model ShopItemModel

@{
    NopHtml.AddCssFileParts("/Plugins/NopStation.Plugin.Misc.FacebookShop/contents/css/Select2.css",string.Empty);
    
    NopHtml.AddScriptParts(ResourceLocation.Footer,"https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js");
    Layout = "_AdminLayout";
    ViewBag.ProductSearchModel = Model.ProductSearchModel;
}

<script>
    $(document).ready(function() {

        $("#@Html.IdFor(model => model.IsOverwriteBrandSelected)").change(toggleBrandDiv);
        toggleBrandDiv();

        $('#@Html.IdFor(model => model.GenderTypeId)').prop('required',true);
        $('#@Html.IdFor(model => model.GoogleProductCategory)').prop('required',true);

        $.ajax({
            url: "@Url.Action("GetGoogleProductCategoriesList", "FacebookShop")",
            type: "GET",
            success: function(data, textStatus, jqXHR)
            {
                var xdata = $.map(data, function (obj) {
                    obj.text = obj.text || obj.name;
                    return obj;
                });

                $('#@Html.IdFor(model => model.GoogleProductCategory)').select2({
                    width: 'resolve',
                    data:xdata,
                    minimumInputLength: 3,
                    placeholder: 'Enter first 3 letters of Product Category',
                    allowClear: true
                });
                $('#@Html.IdFor(model => model.GoogleProductCategory)').val('@Model.GoogleProductCategory'); // Select the option with a value of '1'
                $('#@Html.IdFor(model => model.GoogleProductCategory)').trigger('change'); // Notify any JS components that the value changed
            },
            error: function (request, textStatus, errorThrown) {
                console.log(errorThrown);
            },
            cache: true

        });

    });

    function toggleBrandDiv() {
        if ($('#@Html.IdFor(model => model.IsOverwriteBrandSelected)').is(':checked')) {
            $('#@Html.IdFor(model => model.Brand)').prop('required',true);
            $('#pnlIsOverwriteBrandSelected').show();
        } else {
            $('#@Html.IdFor(model => model.Brand)').prop('required',false);
            $('#pnlIsOverwriteBrandSelected').hide();
        }
    }

</script>

@if (ViewBag.RefreshPage == true)
{
    <script>
        alert("Product Added Successfully!");
    </script>
}

<form asp-controller="FacebookShop" asp-action="BulkItemsAddAll">
    <div style="display: none">
        <div class="col-md-5">
            <div class="form-group row">
                <div class="col-md-4">
                    <nop-label asp-for="ProductSearchModel.SearchProductName" />
                </div>
                <div class="col-md-8">
                    <nop-editor asp-for="ProductSearchModel.SearchProductName" />
                </div>
            </div>
            <div class="form-group row" @(Model.ProductSearchModel.AvailableCategories.SelectionIsNotPossible() ? Html.Raw("style=\"display:none\"") : null)>
                <div class="col-md-4">
                    <nop-label asp-for="ProductSearchModel.SearchCategoryId" />
                </div>
                <div class="col-md-8">
                    <nop-select asp-for="ProductSearchModel.SearchCategoryId" asp-items="Model.ProductSearchModel.AvailableCategories" />
                </div>
            </div>
            <div class="form-group row" @(Model.ProductSearchModel.AvailableCategories.SelectionIsNotPossible() ? Html.Raw("style=\"display:none\"") : null)>
                <div class="col-md-4">
                    <nop-label asp-for="ProductSearchModel.SearchIncludeSubCategories" />
                </div>
                <div class="col-md-8">
                    <nop-editor asp-for="ProductSearchModel.SearchIncludeSubCategories" />
                </div>
            </div>
            <div class="form-group row" @(Model.ProductSearchModel.AvailableManufacturers.SelectionIsNotPossible() ? Html.Raw("style=\"display:none\"") : null)>
                <div class="col-md-4">
                    <nop-label asp-for="ProductSearchModel.SearchManufacturerId" />
                </div>
                <div class="col-md-8">
                    <nop-select asp-for="ProductSearchModel.SearchManufacturerId" asp-items="Model.ProductSearchModel.AvailableManufacturers" />
                </div>
            </div>
            <div class="form-group row" @(Model.ProductSearchModel.AvailableVendors.SelectionIsNotPossible() || Model.ProductSearchModel.IsLoggedInAsVendor ? Html.Raw("style='display: none;' ") : null)>
                <div class="col-md-4">
                    <nop-label asp-for="ProductSearchModel.SearchVendorId" />
                </div>
                <div class="col-md-8">
                    <nop-select asp-for="ProductSearchModel.SearchVendorId" asp-items="Model.ProductSearchModel.AvailableVendors" />
                </div>
            </div>
        </div>
        <div class="col-md-7">
            <div class="form-group row" @(Model.ProductSearchModel.HideStoresList ? Html.Raw("style=\"display:none\"") : null)>
                <div class="col-md-4">
                    <nop-label asp-for="ProductSearchModel.SearchStoreId" />
                </div>
                <div class="col-md-8">
                    <nop-select asp-for="ProductSearchModel.SearchStoreId" asp-items="Model.ProductSearchModel.AvailableStores" />
                </div>
            </div>
            <div class="form-group row" @(Model.ProductSearchModel.AvailableWarehouses.SelectionIsNotPossible() ? Html.Raw("style=\"display:none\"") : null)>
                <div class="col-md-4">
                    <nop-label asp-for="ProductSearchModel.SearchWarehouseId" />
                </div>
                <div class="col-md-8">
                    <nop-select asp-for="ProductSearchModel.SearchWarehouseId" asp-items="Model.ProductSearchModel.AvailableWarehouses" />
                </div>
            </div>
            <div class="form-group row">
                <div class="col-md-4">
                    <nop-label asp-for="ProductSearchModel.SearchProductTypeId" />
                </div>
                <div class="col-md-8">
                    <nop-select asp-for="ProductSearchModel.SearchProductTypeId" asp-items="Model.ProductSearchModel.AvailableProductTypes" />
                </div>
            </div>
            <div class="form-group row">
                <div class="col-md-4">
                    <nop-label asp-for="ProductSearchModel.SearchPublishedId" />
                </div>
                <div class="col-md-8">
                    <nop-select asp-for="ProductSearchModel.SearchPublishedId" asp-items="Model.ProductSearchModel.AvailablePublishedOptions" />
                </div>
            </div>
            <div class="form-group row">
                <div class="col-md-4">
                    <nop-label asp-for="ProductSearchModel.GoDirectlyToSku" />
                </div>
                <div class="col-md-8">
                    <div class="input-group input-group-short">
                        <nop-editor asp-for="ProductSearchModel.GoDirectlyToSku" />
                        <span class="input-group-append">
                            <button type="submit" id="go-to-product-by-sku" name="go-to-product-by-sku" class="btn btn-info btn-flat">
                                @T("Admin.Common.Go")
                            </button>
                        </span>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="content-header clearfix">
        <h1 class="float-left">
            @T("Admin.NopStation.FacebookShop.AddValueForSelectedProduct")
        </h1>
        <div class="float-right">
            &nbsp;
        </div>
    </div>
    <section class="content">
        <div class="container-fluid">
            <div class="form-horizontal">
                <div class="cards-group">
                    <div class="card card-default card-search card-popup">
                        <div class="card-body">
                            <div class="form-group row">
                                <div class="col-md-3">
                                    <nop-label asp-for="GenderTypeId" />
                                </div>
                                <div class="col-md-9">
                                    <nop-select asp-for="GenderTypeId" asp-items="@Model.AvailableGenders" asp-required="true" />
                                    <span asp-validation-for="GenderTypeId"></span>
                                </div>
                            </div>
                            <div class="form-group row">
                                <div class="col-md-3">
                                    <nop-label asp-for="AgeGroupType" />
                                </div>
                                <div class="col-md-9">
                                    <nop-select asp-for="AgeGroupType" asp-items="@Model.AvailableAgeGroups" asp-required="true" />
                                    <span asp-validation-for="AgeGroupType"></span>
                                </div>
                            </div>
                            <div class="form-group row">
                                <div class="col-md-3">
                                    <nop-label asp-for="GoogleProductCategory" />
                                </div>
                                <div class="col-md-9">
                                    <select asp-for="GoogleProductCategory" style="width: 98.50%;"></select>
                                    <span asp-validation-for="GoogleProductCategory"></span>
                                </div>
                            </div>

                            <div class="form-group row">
                                <div class="col-md-3">
                                    <nop-label asp-for="IsOverwriteBrandSelected" />
                                </div>
                                <div class="col-md-9">
                                    <nop-editor asp-for="IsOverwriteBrandSelected" />
                                </div>
                            </div>
                            <nop-nested-setting asp-for="IsOverwriteBrandSelected" id="pnlIsOverwriteBrandSelected">
                                @(await Html.LocalizedEditorAsync<ShopItemModel, ShopItemLocalizedModel>
                                    ("shopitem-info-localized",
                                        @<div>
                                            <div class="form-group row">
                                                <div class="col-md-3">
                                                    <nop-label asp-for="@Model.Locales[item].Brand"/>
                                                </div>
                                                <div class="col-md-9">
                                                    <nop-editor asp-for="@Model.Locales[item].Brand"/>
                                                    <span asp-validation-for="@Model.Locales[item].Brand"></span>
                                                </div>
                                            </div>

                                            <input type="hidden" asp-for="@Model.Locales[item].LanguageId"/>
                                        </div>
                                        , @<div>
                                              <div class="form-group row">
                                                  <div class="col-md-3">
                                                      <nop-label asp-for="Brand"/>
                                                  </div>
                                                  <div class="col-md-9">
                                                      <nop-editor asp-for="Brand" asp-required="true"/>
                                                      <span asp-validation-for="Brand"></span>
                                                  </div>
                                              </div>
                                          </div>)
                                    )
                            </nop-nested-setting>
                        </div>
                        <input type="hidden" asp-for="@Model.ProductSearchModel" />

                        <div class="card-footer">
                            <button type="submit" name="save" class="btn btn-primary" onclick="closeWindow()">
                                <i class="far fa-save"></i>
                                @T("Admin.Common.Save")
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</form>

Areas/Admin/Views/FacebookShop/Configure.cshtml
@using Microsoft.AspNetCore.Http
@model ConfigurationModel
@inject Nop.Core.IWebHelper webHelper

@{
    Layout = "_AdminLayout";
    Html.SetActiveMenuItemSystemName("FacebookShop.Configuration");
    ViewBag.PageTitle = T("Admin.NopStation.FacebookShop.Configuration").Text;
    var configurationDetails = T("Admin.NopStation.FacebookShop.ConfigurationDetails").Text;
    var url = Url.Action("GetCatalogFeed", 
        "FacebookShopCatalog", 
        new { fileName = "catalog_products.csv" },
        webHelper.GetCurrentRequestProtocol()).Replace("/Admin","");
    var configurationDetailsWithFileUrl = configurationDetails?.Replace("_fileUrl_", url);
}

<form asp-controller="FacebookShop" asp-action="Configure" method="post">

    <div class="content-header clearfix">
        <h1 class="float-left">
            @T("Admin.NopStation.FacebookShop.Configuration")
        </h1>
        <div class="float-right">
            <button type="submit" name="save" class="btn btn-primary">
                <i class="far fa-save"></i>
                @T("Admin.Common.Save")
            </button>
        </div>
    </div>

    <section class="content">
        <div class="container-fluid">
            <div class="content-header">
                @Html.Raw(configurationDetailsWithFileUrl)
            </div>
            <div class="form-horizontal">
                @await Component.InvokeAsync("StoreScopeConfiguration")
                <div asp-validation-summary="All"></div>
                <div class="cards-group">
                    <div class="card card-default">
                        <div class="card-body">

                            <div class="form-group row">
                                <div class="col-md-4">
                                    <nop-override-store-checkbox asp-for="PrimaryLanguageId_OverrideForStore" asp-input="PrimaryLanguageId" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                                    <nop-label asp-for="PrimaryLanguageId" />
                                </div>
                                <div class="col-md-8">
                                    <nop-select asp-for="PrimaryLanguageId" asp-items="@Model.AvailableLanguages" />
                                </div>
                            </div>

                            <div class="form-group row">
                                <div class="col-md-4">
                                    <nop-override-store-checkbox asp-for="PrimaryCurrencyId_OverrideForStore" asp-input="PrimaryCurrencyId" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                                    <nop-label asp-for="PrimaryCurrencyId" />
                                </div>
                                <div class="col-md-8">
                                    <nop-select asp-for="PrimaryCurrencyId" asp-items="@Model.AvailableCurrencies" />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</form>

Areas/Admin/Views/FacebookShop/UploadFacebookCatalogCSVFile.cshtml
@model CsvFileUpdateModel

@{
 
    Layout = "_AdminLayout";
}

<form asp-controller="FacebookShop" asp-action="UploadFacebookCatalogCsvFile" enctype="multipart/form-data" onsubmit="return confirm(' @T("Admin.NopStation.FacebookShop.ConfirmSubmit")');">
    <div class="content-header clearfix">
        <h1 class="float-left">
            @T("Admin.NopStation.FacebookShop.UploadYourCSVFile")
        </h1>
        <div class="float-right">
            &nbsp;
        </div>
    </div>
    <section class="content">
        <div class="container-fluid">
            <div class="form-horizontal">
                <div class="cards-group">
                    <div class="card card-default card-search card-popup">
                        <div class="card-body">
                            <div class="form-group row">
                                <div class="col-md-3">
                                    <nop-label asp-for="CatalogFile" />
                                </div>
                                <div class="col-md-9">
                                    <nop-editor asp-for="CatalogFile" asp-required="true"/>
                                    <span asp-validation-for="CatalogFile"></span>
                                </div>
                            </div>
                        </div>
                        <div class="card-footer">
                            <button type="submit" name="save" class="btn btn-primary">
                                <i class="far fa-save"></i>
                                @T("Admin.Common.Save")
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</form>